### ISSUE TITLE
Conflict with vim-textobj-function

### ISSUE THREAD

**Issue by nkakouros** [jeetsukumaran/vim-pythonsense#11]
I have a strange error. I want to use pythonsense with python files and [vim-textobj-function](https://github.com/kana/vim-textobj-function) with other filetypes such as vimscript. Both plugins share the `af`, `if` movements. 

When I open a vimscript file, `:map af` shows the mapping as coming from pythonsense. I looked into the source code for pythonsense and show that the mappings are defined with `<buffer>`. To me, this means that the mappings should not apply to files other than python. Could you help me debug this?

**Comment by echasnovski** [comment]
Hello, @nkakouros.

I just made a PR #15 that addresses this issue. If you don't want to wait for it to be merged, you can either (temporarily) install from my fork or make the exact same changes to your local 'vim-pythonsense' install.

**Comment by nkakouros** [comment]
Thanks @echasnovski!
