### ISSUE TITLE
Motions don't work with async methods/functions

### ISSUE THREAD

**Issue by cmcclellen** [jeetsukumaran/vim-pythonsense#14]
Trying to navigate using the motions, things like ]m pass right over any method or function that is async.

```python
def foo():
  pass

async def bar():
  pass

def baz():
  pass
```

If you sit on foo() and hit ]m it will jump to baz.  Same for methods in classes.  The text objects seem to work just fine though.

**Comment by jeetsukumaran** [comment]
Hi, would happily accept a PR for this if you have the time to work on it.
