### ISSUE TITLE
How about `c` instead of `k` for class?

### ISSUE THREAD

**Issue by cliffxuan** [jeetsukumaran/vim-pythonsense#16]
First of all, thank you for making this plugin.

This is a question rather than a bug, and I know I can set this mapping myself and have already done it.

Just wondering in the alternative keymap, what the rationale is for choosing `]k` instead of `]c` for class motions? Firstly, `c` is the initial for `class` therefore it's more intuitive.  Secondly, `[`, `]` and `k` are both on the right side of the keyboard, but `c` is on the left side. To me, this is more ergonomic.

**Comment by jeetsukumaran** [comment]
IIRC, "ic" was used by some native or otherwise pre-defined binding.

You can map it to whatever you want, including 'ic', overriding the already defined one.
